import {Projects} from '/projects';

export const PROJECTS: Projects[]=[  
   {  
      sno:0,
      amtpledged:15823,
      blurb:"'Catalysts, Explorers & Secret Keepers: Women of Science Fiction' is a take-home exhibit & anthology by the Museum of Science Fiction",
      by:"Museum of Science Fiction",
      country:"US",
      currency:"usd",
      "endtime:"2016-11-01T23:59:00-04:00",
      location:"Washington, DC",
      percentagefunded:186,
      numbackers:"219382",
      state:"DC",
      title:"Catalysts, Explorers & Secret Keepers: Women of SF",
      type:"Town",
      url:"/projects/1608905146/catalysts-explorers-and-secret-keepers-women-of-sf?ref=discovery"
   },
   {  
      "sno":1,
      "amtpledged":6859,
      "blurb":"A unique handmade picture book for kids & art lovers about a nervous monster who finds his courage with the help of a brave little girl",
      "by":"Tyrone Wells & Broken Eagle, LLC",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-25T01:13:33-05:00",
      "location":"Portland, OR",
      "percentagefunded":8,
      "numbackers":"154926",
      "state":"OR",
      "title":"The Whatamagump (a hand-crafted story picture book)",
      "type":"Town",
      "url":"/projects/thewhatamagump/the-whatamagump-a-hand-crafted-story-picture-book?ref=discovery"
   },
   {  
      "sno":2,
      "amtpledged":17906,
      "blurb":"A horror comedy about a repairman who was in the wrong place at the wrong time thanks to mad scientists and monsters",
      "by":"Tessa Stone",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-23T23:00:00-05:00",
      "location":"Los Angeles, CA",
      "percentagefunded":102,
      "numbackers":"105857",
      "state":"CA",
      "title":"Not Drunk Enough Volume 1!",
      "type":"Town",
      "url":"/projects/1890925998/not-drunk-enough-volume-1?ref=discovery"
   },
   {  
      "sno":3,
      "amtpledged":67081,
      "blurb":"The Johnny Wander autobio omnibus you've all been asking for! Over 400 pages of comics and extras over the years!",
      "by":"Johnny Wander",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-01T23:50:00-04:00",
      "location":"Brooklyn, NY",
      "percentagefunded":191,
      "numbackers":"91585",
      "state":"NY",
      "title":"Our Cats Are More Famous Than Us: A Johnny Wander Omnibus",
      "type":"County",
      "url":"/projects/746734715/our-cats-are-more-famous-than-us-a-johnny-wander-o?ref=discovery"
   },
   {  
      "sno":4,
      "amtpledged":32772,
      "blurb":"The vision for this project is the establishment of a women-owned craft brewery in Rwanda",
      "by":"Beau's All Natural Brewing Company",
      "country":"RW",
      "currency":"cad",
      "endtime":"2016-11-18T23:05:48-05:00",
      "location":"Kigali, Rwanda",
      "percentagefunded":34,
      "numbackers":"87142",
      "state":"Kigali Province",
      "title":"The Rwanda Craft Brewery Project",
      "type":"Town",
      "url":"/projects/beaus/the-rwanda-craft-brewery-project?ref=discovery"
   },
   {  
      "sno":5,
      "amtpledged":2065,
      "blurb":"In Shiraz, traditional and modern family recipes tell a story of inherited love through delicious Persian comfort food",
      "by":"Shireen Rahimi",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-28T00:00:00-05:00",
      "location":"Miami, FL",
      "percentagefunded":114,
      "numbackers":"78471",
      "state":"FL",
      "title":"Shiraz the Cookbook",
      "type":"Town",
      "url":"/projects/844448164/shiraz-the-cookbook?ref=discovery"
   },
   {  
      "sno":6,
      "amtpledged":577844,
      "blurb":"Polygons is the origami-like measuring spoon that lays flat and folds to 4 different sizes to fit your cooking and baking needs ",
      "by":"Polygons Design",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-20T11:57:34-05:00",
      "location":"Wilmington, DE",
      "percentagefunded":5778,
      "numbackers":"74405",
      "state":"DE",
      "title":"Polygons | The Flat 4-in-1 Measuring Spoon",
      "type":"Town",
      "url":"/projects/stillalive/polygons-the-flat-4-in-1-measuring-spoon?ref=discovery"
   },
   {  
      "sno":7,
      "amtpledged":4952,
      "blurb":"This hardcover coffee table book showcases all the whimsical illustrations from professional book illustrator Lee White",
      "by":"Lee White",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-28T15:00:00-05:00",
      "location":"Portland, OR",
      "percentagefunded":42,
      "numbackers":"73986",
      "state":"OR",
      "title":"Illumination: The Art of Lee White",
      "type":"Town",
      "url":"/projects/987803560/illumination-the-art-of-lee-white?ref=discovery"
   },
   {  
      "sno":8,
      "amtpledged":45959,
      "blurb":"A heartfelt film exploring families and relationships between Korean and African American communities set during the LA Riots",
      "by":"Justin Chon",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-09T19:27:32-05:00",
      "location":"Los Angeles, CA",
      "percentagefunded":153,
      "numbackers":"73206",
      "state":"CA",
      "title":"GOOK - A Korean American LA Riots Film",
      "type":"Town",
      "url":"/projects/2084768431/gook-a-korean-american-la-riots-film?ref=discovery"
   },
   {  
      "sno":9,
      "amtpledged":214035,
      "blurb":"A Smartphone Mount That Helps You Capture The Moment With Facial Tracking, Automated Videos and Pictures, Timelapse and Panoramas",
      "by":"Stacked",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-10-30T06:21:30-04:00",
      "location":"Los Angeles, CA",
      "percentagefunded":611,
      "numbackers":"70122",
      "state":"CA",
      "title":"Picbot - An Automated Motorized Picture And Video Bot",
      "type":"Town",
      "url":"/projects/1597931194/picbot-an-automated-motorized-picture-and-video-bo?ref=discovery"
   },
   {  
      "sno":10,
      "amtpledged":41025,
      "blurb":"Who's watching when a fracked oil pipeline sparks the Standing Rock Sioux Nation to lead the biggest indigenous protest in 100 years?",
      "by":"Raviv Ullman",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-22T23:30:00-05:00",
      "location":"Cannon Ball, ND",
      "percentagefunded":54,
      "numbackers":"69320",
      "state":"ND",
      "title":"Standing Ground - A Documentary Film",
      "type":"Town",
      "url":"/projects/345639715/standing-ground-a-documentary-film?ref=discovery"
   },
   {  
      "sno":11,
      "amtpledged":45396,
      "blurb":"Master your time with a hybrid paper-digital planning system powered by augmented reality ",
      "by":"Evopaper",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-26T02:55:00-05:00",
      "location":"San Francisco, CA",
      "percentagefunded":129,
      "numbackers":"68929",
      "state":"CA",
      "title":"Slice Planner: First Notebook Connected to Digital Calendars",
      "type":"Town",
      "url":"/projects/sliceplanner/slice-planner-first-notebook-connected-to-digital?ref=discovery"
   },
   {  
      "sno":12,
      "amtpledged":4621,
      "blurb":"Thrills! Chills!  The daring show you cannot miss!  Step right up and dare to witness a new spin on classic horror",
      "by":"ThunderCrab Studios",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-16T00:00:46-05:00",
      "location":"Columbus, OH",
      "percentagefunded":30,
      "numbackers":"67226",
      "state":"OH",
      "title":"The Mechanical Dancer - an animated short film",
      "type":"Town",
      "url":"/projects/23022585/the-mechanical-dancer-an-animated-short-film?ref=discovery"
   },
   {  
      "sno":13,
      "amtpledged":30170,
      "blurb":"A collection of landmark American films directed by women, digitally restored from archive film elements, loaded with bonus content",
      "by":"Kino Lorber",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-18T16:22:53-05:00",
      "location":"New York, NY",
      "percentagefunded":68,
      "numbackers":"66673",
      "state":"NY",
      "title":"PIONEERS: FIRST WOMEN FILMMAKERS",
      "type":"Town",
      "url":"/projects/kinolorber/pioneers-first-women-filmmakers?ref=discovery"
   },
   {  
      "sno":14,
      "amtpledged":13138,
      "blurb":"A graphic novel about two magical ladies in love",
      "by":"Pat Shand",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-02T20:00:00-04:00",
      "location":"New York, NY",
      "percentagefunded":65,
      "numbackers":"64867",
      "state":"NY",
      "title":"Destiny, NY",
      "type":"Town",
      "url":"/projects/248241887/destiny-ny-a-graphic-novel?ref=discovery"
   },
   {  
      "sno":15,
      "amtpledged":1751,
      "blurb":"In this dance film, a teenage girl must convince herself and her mother she has what it takes to make it as a professional ballerina",
      "by":"Tati & Anthony Vogt",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-25T08:25:18-05:00",
      "location":"Phoenix, AZ",
      "percentagefunded":11,
      "numbackers":"63758",
      "state":"AZ",
      "title":"On Pointe",
      "type":"Town",
      "url":"/projects/onpointefilm/on-pointe?ref=discovery"
   },
   {  
      "sno":16,
      "amtpledged":37857,
      "blurb":"This ain't cherry chapstick It's lip balm for men Handmade by the fellas that started it",
      "by":"Chad Lieske",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-10T10:03:09-05:00",
      "location":"Venice, Los Angeles, CA",
      "percentagefunded":135,
      "numbackers":"63416",
      "state":"CA",
      "title":"Lucky Bastard Co Original Handmade Gentlemen's Lip Balm",
      "type":"Suburb",
      "url":"/projects/1433655996/lucky-bastard-co-original-handmade-gentlemens-lip?ref=discovery"
   },
   {  
      "sno":17,
      "amtpledged":30191,
      "blurb":"Ready, set, fold ! A new way to do papercraft in instant Using colorful high quality, super solid and water drop resistant paper",
      "by":"DT WORKSHOP",
      "country":"FR",
      "currency":"eur",
      "endtime":"2016-11-02T18:59:00-04:00",
      "location":"Paris, France",
      "percentagefunded":150,
      "numbackers":"62642",
      "state":"Ile-de-France",
      "title":"Introducing 3 DIY papercraft kits no need glue or scissors",
      "type":"Town",
      "url":"/projects/dtworkshop/introducing-3-diy-papercraft-kits-without-glue-or?ref=discovery"
   },
   {  
      "sno":18,
      "amtpledged":110431,
      "blurb":"One of the Most Successful Shoes on Kickstarter introduces its Newest & Best Collection for MEN & WOMEN Handmade in Italy",
      "by":"Kabaccha Shoes",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-30T22:00:00-05:00",
      "location":"Miami Beach, FL",
      "percentagefunded":441,
      "numbackers":"61290",
      "state":"FL",
      "title":"Beautiful Italian Shoes for Men & Women",
      "type":"Town",
      "url":"/projects/1798878014/beautiful-italian-shoes-for-men-and-women?ref=discovery"
   },
   {  
      "sno":19,
      "amtpledged":10018,
      "blurb":"Map T-shirts and map posters showing detailed cities all over the world â€“ now with over 230 locations",
      "by":"Alex Szabo-Haslam",
      "country":"GB",
      "currency":"gbp",
      "endtime":"2016-11-09T08:56:57-05:00",
      "location":"Sheffield, UK",
      "percentagefunded":1001,
      "numbackers":"48270",
      "state":"England",
      "title":"Citee: map T-shirts and map posters",
      "type":"Town",
      "url":"/projects/szabohaslam/citee-map-t-shirts-and-map-posters?ref=discovery"
   },
   {  
      "sno":20,
      "amtpledged":192915,
      "blurb":"Vue is the world's first pair of smart glasses that are designed for everyday use Offered in prescription, plano, and sunglasses",
      "by":"Vue",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-12-09T20:00:00-05:00",
      "location":"San Francisco, CA",
      "percentagefunded":385,
      "numbackers":"46520",
      "state":"CA",
      "title":"Vue: Your Everyday Smart Glasses",
      "type":"Town",
      "url":"/projects/1093823090/vue-your-everyday-smart-glasses?ref=discovery"
   },
   {  
      "sno":21,
      "amtpledged":2111,
      "blurb":"When a naive wish comes true, five misfits must battle real-life movie monsters A comedy-horror fundraising for a feature film!",
      "by":"Cartridge Thunder",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-26T11:41:44-05:00",
      "location":"Chicago, IL",
      "percentagefunded":2,
      "numbackers":"44949",
      "state":"IL",
      "title":"Journey to Burger Town",
      "type":"Town",
      "url":"/projects/cartridgethunder/journey-to-burger-town?ref=discovery"
   },
   {  
      "sno":22,
      "amtpledged":7728,
      "blurb":"Deep-space oil paintings & fine art prints, featuring breathtaking galaxies, nebulae, and black holes Art for awesome nerdy people",
      "by":"Cathrin Machin",
      "country":"AU",
      "currency":"aud",
      "endtime":"2016-11-27T22:18:49-05:00",
      "location":"Sydney, AU",
      "percentagefunded":193,
      "numbackers":"44162",
      "state":"NSW",
      "title":"Beautifully Nerdy Deep Space Paintings & Prints - FQTQ",
      "type":"Town",
      "url":"/projects/cathrin/beautifully-nerdy-deep-space-paintings-and-prints?ref=discovery"
   },
   {  
      "sno":23,
      "amtpledged":11590,
      "blurb":"Photography book documenting the locations of forty-two reggae record covers photographed in London between 1967 and 1987",
      "by":"Alex Bartsch",
      "country":"GB",
      "currency":"gbp",
      "endtime":"2016-12-06T16:00:00-05:00",
      "location":"London, UK",
      "percentagefunded":77,
      "numbackers":"42713",
      "state":"England",
      "title":"Covers: Retracing Reggae Record Sleeves in London",
      "type":"Town",
      "url":"/projects/1060504029/covers-retracing-reggae-record-sleeves-in-london?ref=discovery"
   },
   {  
      "sno":24,
      "amtpledged":12856,
      "blurb":"A guidebook of curious and creative activities to cultivate joy, wonder, and discovery in you and your garden",
      "by":"Gayla Trail of You Grow Girl",
      "country":"CA",
      "currency":"cad",
      "endtime":"2016-11-03T22:00:00-04:00",
      "location":"Toronto, Canada",
      "percentagefunded":64,
      "numbackers":"41733",
      "state":"ON",
      "title":"Grow Curious: A Gardener's Creative Activity Book",
      "type":"Town",
      "url":"/projects/yougrowgirl/grow-curious-a-gardeners-creative-activity-book?ref=discovery"
   },
   {  
      "sno":25,
      "amtpledged":21625,
      "blurb":"Let's enable movement while upholding cultural beliefs, because all girls deserve to play #MuslimsPlayStuff",
      "by":"ASIYAâ„¢ Modest Activewear",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-17T11:05:44-05:00",
      "location":"Minneapolis, MN",
      "percentagefunded":86,
      "numbackers":"39560",
      "state":"MN",
      "title":"ASIYAâ„¢: Activewear Designed to Enable Muslim Athletes",
      "type":"Town",
      "url":"/projects/1913748268/asiyatm-activewear-designed-to-enable-muslim-athle?ref=discovery"
   },
   {  
      "sno":26,
      "amtpledged":50706,
      "blurb":"The story of an international anti-cultwhose radical search for personal liberation incurred the wrath of British authorities",
      "by":"Unclean Pictures",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-03T23:00:00-04:00",
      "location":"New York, NY",
      "percentagefunded":101,
      "numbackers":"36781",
      "state":"NY",
      "title":"A MESSAGE FROM THE TEMPLE",
      "type":"Town",
      "url":"/projects/uncleanpictures/a-message-from-the-temple?ref=discovery"
   },
   {  
      "sno":27,
      "amtpledged":9851,
      "blurb":"Gang tattoos are digitally removed from portraits of ex-gang members Powerful and emotionally charged interviews follow",
      "by":"Steven Burton",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-12T13:11:32-05:00",
      "location":"Los Angeles, CA",
      "percentagefunded":39,
      "numbackers":"36276",
      "state":"CA",
      "title":"Skin deep, ex-gang members looking beyond the tattoos",
      "type":"Town",
      "url":"/projects/1657996647/skin-deep-ex-gang-members-looking-beyond-the-tatto?ref=discovery"
   },
   {  
      "sno":28,
      "amtpledged":70642,
      "blurb":"Fire, blood & Vikings! Stories from a time when kingdoms were forged in battle & the old ways still survived",
      "by":"Ben Templesmith",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-02T09:58:00-04:00",
      "location":"Seattle, WA",
      "percentagefunded":743,
      "numbackers":"35384",
      "state":"WA",
      "title":"BLOOD SONGS",
      "type":"Town",
      "url":"/projects/templesmith/blood-songs?ref=discovery"
   },
   {  
      "sno":29,
      "amtpledged":123660,
      "blurb":"A Small, Portable Hardware Password Keeper to Keep Your Passwords Safe Wherever You Are",
      "by":"Stephan Electronics",
      "country":"CH",
      "currency":"chf",
      "endtime":"2016-11-07T10:16:51-05:00",
      "location":"Lausanne, Switzerland",
      "percentagefunded":247,
      "numbackers":"34565",
      "state":"Canton of Vaud",
      "title":"Mooltipass Mini - Your Passwords On The Go!",
      "type":"Town",
      "url":"/projects/limpkin/mooltipass-mini-your-passwords-on-the-go?ref=discovery"
   },
   {  
      "sno":30,
      "amtpledged":8544,
      "blurb":"The perfect bra at the click of a button",
      "by":"Founder Danai L Pointer",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-26T22:00:00-05:00",
      "location":"New York, NY",
      "percentagefunded":42,
      "numbackers":"34397",
      "state":"NY",
      "title":"TruNudeâ„¢",
      "type":"Town",
      "url":"/projects/875623672/trunudetm?ref=discovery"
   },
   {  
      "sno":31,
      "amtpledged":26107,
      "blurb":"Art print and coloring book of a massive 6-foot-wide hand-drawn school loaded with clever gags, secret surprises and pink donuts",
      "by":"scott teplin",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-04T21:00:00-04:00",
      "location":"Brooklyn, NY",
      "percentagefunded":274,
      "numbackers":"33741",
      "state":"NY",
      "title":"BIG SCHOOL: Huge, maniacal drawing for print & coloring book",
      "type":"County",
      "url":"/projects/teplin/big-school-huge-maniacal-drawing-for-print-and-col?ref=discovery"
   },
   {  
      "sno":32,
      "amtpledged":11330,
      "blurb":"Deluxe Mac&Cheese Kits that are as good as homemade Our recipe creates an authentic bechamel-cheese sauce & includes a crouton topping",
      "by":"Chris McMurray",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-20T16:55:44-05:00",
      "location":"Brooklyn, NY",
      "percentagefunded":566,
      "numbackers":"31774",
      "state":"NY",
      "title":"Mac & Son - Mac & Cheese made better",
      "type":"County",
      "url":"/projects/1588077822/mac-and-son-mac-and-cheese-made-better?ref=discovery"
   },
   {  
      "sno":33,
      "amtpledged":5908,
      "blurb":"A photography book filled with amazing pictures showcasing the diversity in colors and the life of street vendors in Hanoi",
      "by":"Loes Heerink",
      "country":"VN",
      "currency":"eur",
      "endtime":"2016-11-14T09:33:39-05:00",
      "location":"Hanoi, Viet Nam",
      "percentagefunded":159,
      "numbackers":"31497",
      "state":"Ha Noi",
      "title":"Unique photo book highlighting the beauty of street vendors",
      "type":"Town",
      "url":"/projects/125851434/vendors?ref=discovery"
   },
   {  
      "sno":34,
      "amtpledged":21390,
      "blurb":"A colourful illustrated guide to the mythical creatures from Celtic myth, believed to inhabit the dramatic landscapes of Wales",
      "by":"Collette June Ellis",
      "country":"GB",
      "currency":"gbp",
      "endtime":"2016-11-06T10:59:53-05:00",
      "location":"Wales, UK",
      "percentagefunded":1069,
      "numbackers":"31178",
      "state":"England",
      "title":"An Illustrated Guide to Welsh Monsters & Mythical Beasts",
      "type":"Town",
      "url":"/projects/collettejellis/an-illustrated-guide-to-welsh-monsters-and-mythica?ref=discovery"
   },
   {  
      "sno":35,
      "amtpledged":194009,
      "blurb":"Next level competitive miniature Board Game for 1-4 players from creator of Neuroshima Hex and Cry Havoc",
      "by":"Awaken Realms",
      "country":"PL",
      "currency":"gbp",
      "endtime":"2016-11-14T12:12:22-05:00",
      "location":"Wroclaw, Poland",
      "percentagefunded":485,
      "numbackers":"30546",
      "state":"Lower Silesia",
      "title":"The Edge: Dawnfall",
      "type":"Town",
      "url":"/projects/awakenrealms/the-edge-dawnfall?ref=discovery"
   },
   {  
      "sno":36,
      "amtpledged":35313,
      "blurb":"We need your help to Prove Love Is Real and make a FREE Chuck Tingle Adventure Game for all True Buckaroos Who Kiss",
      "by":"ZoÃ« Quinn",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-16T11:40:11-05:00",
      "location":"Los Angeles, CA",
      "percentagefunded":50,
      "numbackers":"28818",
      "state":"CA",
      "title":"Kickstarted in the Butt: A Chuck Tingle Digital Adventure",
      "type":"Town",
      "url":"/projects/703752115/kickstarted-in-the-butt-a-chuck-tingle-digital-adv?ref=discovery"
   },
   {  
      "sno":37,
      "amtpledged":52349,
      "blurb":"Andy Irons, 3-time world champion surfer who lived at the extremes of emotion, chased success only to be faced with challenges on shore",
      "by":"Teton Gravity Research",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-12T12:54:52-05:00",
      "location":"Jackson, WY",
      "percentagefunded":34,
      "numbackers":"28274",
      "state":"WY",
      "title":"ANDY: The Untold Story of Andy Irons",
      "type":"Town",
      "url":"/projects/tetongravity/the-untold-story-of-andy-irons?ref=discovery"
   },
   {  
      "sno":38,
      "amtpledged":14442,
      "blurb":"Tired of getting your news from sources funded by mega-corporations? Newsbudâ€”100% people-funded media Where media integrity matters",
      "by":"Sibel Edmonds",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-27T02:04:46-05:00",
      "location":"Bend, OR",
      "percentagefunded":11,
      "numbackers":"27060",
      "state":"OR",
      "title":"Support a 100% People-Funded Mediaâ€”Newsbud, Phase 2",
      "type":"Town",
      "url":"/projects/141490519/support-a-100-people-funded-medianewsbud-phase-2?ref=discovery"
   },
   {  
      "sno":39,
      "amtpledged":334324,
      "blurb":"Join us on our journey to preserve an American icon #KeepThemRuby",
      "by":"Smithsonian Institution",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-16T23:59:00-05:00",
      "location":"Washington, DC",
      "percentagefunded":111,
      "numbackers":"26457",
      "state":"DC",
      "title":"Conserve Dorothy's RUBY SLIPPERS",
      "type":"Town",
      "url":"/projects/smithsonian/conserve-dorothys-ruby-slippers?ref=discovery"
   },
   {  
      "sno":40,
      "amtpledged":43926,
      "blurb":"comp is a redesign of the classic composition notebookâ€“â€“made for the 21st century ",
      "by":"Aron Fay",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-23T18:00:00-05:00",
      "location":"Manhattan, NY",
      "percentagefunded":55,
      "numbackers":"26359",
      "state":"NY",
      "title":"comp",
      "type":"County",
      "url":"/projects/comp/comp?ref=discovery"
   },
   {  
      "sno":41,
      "amtpledged":8445,
      "blurb":"We are two best friends/sisters whose dream is to share our buttery, smooth, melt-in-your-mouth caramels with you!",
      "by":"Alysia and Tammy Lok",
      "country":"CA",
      "currency":"cad",
      "endtime":"2016-11-25T09:30:49-05:00",
      "location":"Edmonton, Canada",
      "percentagefunded":64,
      "numbackers":"25681",
      "state":"AB",
      "title":"Caramia Caramels",
      "type":"Town",
      "url":"/projects/1746625989/caramia-caramels?ref=discovery"
   },
   {  
      "sno":42,
      "amtpledged":20537,
      "blurb":"I've been living on the road, writing the songs, and now I'm ready to head in to the studio- with your help! Let's make this album!",
      "by":"Chelsea Berry",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-10-30T15:38:36-04:00",
      "location":"Gloucester, MA",
      "percentagefunded":114,
      "numbackers":"24883",
      "state":"MA",
      "title":"You and Chelsea Berry making a new album!",
      "type":"Town",
      "url":"/projects/chelseaberry/you-and-chelsea-berry-making-a-new-album?ref=discovery"
   },
   {  
      "sno":43,
      "amtpledged":19852,
      "blurb":"Localizing and publishing Osamu Tezukaâ€™s dark anthology works Prepare yourself! And a special reintroduction to: The Crater !!!",
      "by":"digitalmanga",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-26T13:59:52-05:00",
      "location":"Gardena, CA",
      "percentagefunded":79,
      "numbackers":"24346",
      "state":"CA",
      "title":"Re-Launch of Tezuka's - Under the Air (Classic Manga)",
      "type":"Town",
      "url":"/projects/digitalmanga/re-launch-of-tezukas-under-the-air-classic-manga?ref=discovery"
   },
   {  
      "sno":44,
      "amtpledged":20225,
      "blurb":"A 36 card Lenormand divination deck of surreal symbolism, and the final companion deck to The Wooden Tarot and Earthbound Oracle",
      "by":"Andy Swartz",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-10-31T19:00:00-04:00",
      "location":"Atlanta, GA",
      "percentagefunded":518,
      "numbackers":"24150",
      "state":"GA",
      "title":"The Seeker's Lenormand Deck",
      "type":"Town",
      "url":"/projects/skullgarden/the-seekers-lenormand-deck?ref=discovery"
   },
   {  
      "sno":45,
      "amtpledged":16297,
      "blurb":"Villains are bad tempered guys, what if we try to change that by giving them some love?",
      "by":"Nacho Diaz",
      "country":"ES",
      "currency":"eur",
      "endtime":"2016-11-09T13:03:47-05:00",
      "location":"Barcelona, Spain",
      "percentagefunded":325,
      "numbackers":"23999",
      "state":"Catalonia",
      "title":"Villains Need Love - Art Book",
      "type":"Town",
      "url":"/projects/naolito/villains-need-love-art-book?ref=discovery"
   },
   {  
      "sno":46,
      "amtpledged":7152,
      "blurb":"Planned to make an album Didn't plan to have a coma Had a coma Now I'm back to making an album with your help Let's do this!",
      "by":"Julia Weldon",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-24T08:28:09-05:00",
      "location":"Brooklyn, NY",
      "percentagefunded":47,
      "numbackers":"23626",
      "state":"NY",
      "title":"Julia Weldon: Alive! and Making a New Album",
      "type":"County",
      "url":"/projects/2146098307/julia-weldon-alive-and-making-a-new-album?ref=discovery"
   },
   {  
      "sno":47,
      "amtpledged":14322,
      "blurb":"When an aged mortal man and immortal vampire fall in love, painful realities about deathâ€”and the deathlessâ€”interfere",
      "by":"IronSpike",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-23T16:00:30-05:00",
      "location":"Chicago, IL",
      "percentagefunded":179,
      "numbackers":"23331",
      "state":"IL",
      "title":"Letters for Lucardo: An Erotic Graphic Novel",
      "type":"Town",
      "url":"/projects/ironspike/letters-for-lucardo-an-erotic-graphic-novel?ref=discovery"
   },
   {  
      "sno":48,
      "amtpledged":40070,
      "blurb":"A picture book adaptation of the classical On The Origin Of Species Great for children and grownups!",
      "by":"Sabina Radeva",
      "country":"GB",
      "currency":"gbp",
      "endtime":"2016-11-09T09:41:26-05:00",
      "location":"Oxford, UK",
      "percentagefunded":2108,
      "numbackers":"22844",
      "state":"England",
      "title":"Darwinâ€™s On the Origin of Species: A Picture Book Adaptation",
      "type":"Town",
      "url":"/projects/1128391174/darwins-on-the-origin-of-species-a-picture-book-ad?ref=discovery"
   },
   {  
      "sno":49,
      "amtpledged":36662,
      "blurb":"Once again, show us your love and support Make a generous donation for the Season 8 of the Invisible Dog!",
      "by":"Lucien Zayan",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-09T18:30:00-05:00",
      "location":"Brooklyn, NY",
      "percentagefunded":146,
      "numbackers":"22361",
      "state":"NY",
      "title":"THE INVISIBLE DOG - SEASON 8",
      "type":"County",
      "url":"/projects/183275255/the-invisible-dog-season-8?ref=discovery"
   },
   {  
      "sno":50,
      "amtpledged":4111,
      "blurb":"Help make room in the Kill Rock Stars office by purchasing CDs, LPs, and cassettes at a serious discount!",
      "by":"kill rock stars",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-24T14:13:33-05:00",
      "location":"Portland, OR",
      "percentagefunded":411,
      "numbackers":"22322",
      "state":"OR",
      "title":"Help Kill Rock Stars make room in the office for 2017!",
      "type":"Town",
      "url":"/projects/killrockstars/help-kill-rock-stars-make-room-in-the-office-for-2?ref=discovery"
   },
   {  
      "sno":51,
      "amtpledged":38678,
      "blurb":"Build a language, build a world Who were the Isolation, and how were they lost? In this game, your language is the story",
      "by":"Thorny Games",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-12-09T02:00:00-05:00",
      "location":"San Francisco, CA",
      "percentagefunded":1289,
      "numbackers":"22195",
      "state":"CA",
      "title":"Dialect: A Game about Language and How it Dies",
      "type":"Town",
      "url":"/projects/347698129/dialect-a-game-about-language-and-how-it-dies?ref=discovery"
   },
   {  
      "sno":52,
      "amtpledged":5103,
      "blurb":"Your favorite giraffestronaut and robot are back, and this time they're forming a rescue party to search for a missing Mars rover",
      "by":"Andrew Rader",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-12-01T02:59:00-05:00",
      "location":"Los Angeles, CA",
      "percentagefunded":51,
      "numbackers":"21975",
      "state":"CA",
      "title":"Mars Rover Rescue",
      "type":"Town",
      "url":"/projects/1734237858/mars-rover-rescue?ref=discovery"
   },
   {  
      "sno":53,
      "amtpledged":10658,
      "blurb":"Help Copper Canyon Press publish the definitive collection of WS Merwinâ€™s poetry",
      "by":"Copper Canyon Press",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-12-01T20:00:00-05:00",
      "location":"Seattle, WA",
      "percentagefunded":21,
      "numbackers":"21858",
      "state":"WA",
      "title":"The Essential WS Merwin",
      "type":"Town",
      "url":"/projects/896286441/the-essential-ws-merwin?ref=discovery"
   },
   {  
      "sno":54,
      "amtpledged":5811,
      "blurb":"Make your holidays a little stranger with these 4 King in Yellow inspired Christmas cards beautifully illustrated by Heather Hudson",
      "by":"Studio WonderCabinet",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-15T23:00:00-05:00",
      "location":"Seattle, WA",
      "percentagefunded":290,
      "numbackers":"Cambridge, MA",
      "state":"WA",
      "title":"The King in Yellow Christmas Cards",
      "type":"Town",
      "url":"/projects/1464564021/the-king-in-yellow-christmas-cards?ref=discovery"
   },
   {  
      "sno":55,
      "amtpledged":5184,
      "blurb":"JazzNESs: A NES Classic Jazz Tributeis a jazz cover CD which encompasses Jazz Piano Trio arrangements of NES Classics",
      "by":"Brian Ibbott",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-22T15:47:33-05:00",
      "location":"Arvada, CO",
      "percentagefunded":60,
      "numbackers":"21625",
      "state":"CO",
      "title":"JazzNESs: A Nintendo Classic Jazz Tribute",
      "type":"Town",
      "url":"/projects/coverville/jazzness-a-nintendo-classic-jazz-tribute?ref=discovery"
   },
   {  
      "sno":56,
      "amtpledged":7580,
      "blurb":"My Name Is Stardust was inspired by what Neil DeGrasse Tyson called â€œthe most astounding factâ€- that we are literally made of stardust",
      "by":"Douglas Harris",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-17T08:01:11-05:00",
      "location":"Salt Lake City, UT",
      "percentagefunded":59,
      "numbackers":"21455",
      "state":"UT",
      "title":"My Name Is Stardust: Children's Book About Science",
      "type":"Town",
      "url":"/projects/doughded/childrens-book-my-name-is-stardust?ref=discovery"
   },
   {  
      "sno":57,
      "amtpledged":218565,
      "blurb":"Carcel is a fashion label from Copenhagen produced by women in prison and made from 100% natural materials",
      "by":"Carcel",
      "country":"DK",
      "currency":"dkk",
      "endtime":"2016-11-24T05:10:23-05:00",
      "location":"Copenhagen, Denmark",
      "percentagefunded":145,
      "numbackers":"21412",
      "state":"Hovedstaden",
      "title":"Danish Designer Wear - Made by Women in Prison",
      "type":"Town",
      "url":"/projects/1944171683/danish-designer-wear-made-by-women-in-prison?ref=discovery"
   },
   {  
      "sno":58,
      "amtpledged":4522,
      "blurb":"Immortal Prosperity is a premium, highly-detailed coloring book featuring dragons and phoenixes It is designed for people of all ages",
      "by":"Art The Culture",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-25T18:55:24-05:00",
      "location":"Brooklyn, NY",
      "percentagefunded":116,
      "numbackers":"20915",
      "state":"NY",
      "title":"Immortal Prosperity: First Dragon & Phoenix Coloring Book",
      "type":"County",
      "url":"/projects/2066577066/immortal-prosperity-first-dragon-and-phoenix-color?ref=discovery"
   },
   {  
      "sno":59,
      "amtpledged":6354,
      "blurb":"The Printed Walk is a letterpress-printed chronicle of an artist's 2017 thru-hike of the Appalachian Trail",
      "by":"Lindsay Schmittle",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-12-04T12:48:48-05:00",
      "location":"Landenberg, PA",
      "percentagefunded":44,
      "numbackers":"20787",
      "state":"PA",
      "title":"The Printed Walk: Georgia to Maine",
      "type":"Town",
      "url":"/projects/185016739/the-printed-walk-georgia-to-maine?ref=discovery"
   },
   {  
      "sno":60,
      "amtpledged":15014,
      "blurb":"A story of a girl that marches to the beat of her own imagination",
      "by":"Katie Newell",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-01T15:06:16-04:00",
      "location":"Grand Rapids, MI",
      "percentagefunded":333,
      "numbackers":"New York, NY",
      "state":"MI",
      "title":"I'd Rather Be A Dragon",
      "type":"Town",
      "url":"/projects/1226138705/id-rather-be-a-dragon?ref=discovery"
   },
   {  
      "sno":61,
      "amtpledged":10897,
      "blurb":"Playing cards that offer beer information and casual tasting guidance for the many conversations that happen over beer",
      "by":"Dave Shea",
      "country":"CA",
      "currency":"cad",
      "endtime":"2016-11-18T17:00:00-05:00",
      "location":"Vancouver, Canada",
      "percentagefunded":27,
      "numbackers":"20042",
      "state":"BC",
      "title":"The Palate Deck: Playing Cards for Beer Tasting",
      "type":"Town",
      "url":"/projects/mezzoblue/the-palate-deck-playing-cards-for-beer-tasting?ref=discovery"
   },
   {  
      "sno":62,
      "amtpledged":272841,
      "blurb":"A 45 min sandbox adventure for 1-4 players w/ limited action selection, grid movement, press-your-luck & Item-Holding Meeples!",
      "by":"Gamelyn Games",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-27T01:59:00-05:00",
      "location":"Phoenix, AZ",
      "percentagefunded":1818,
      "numbackers":"19829",
      "state":"AZ",
      "title":"Tiny Epic Quest - Introducing ITEMeeplesâ„¢",
      "type":"Town",
      "url":"/projects/coe/tiny-epic-quest-introducing-itemeeplestm?ref=discovery"
   },
   {  
      "sno":63,
      "amtpledged":32475,
      "blurb":"Geeky inside, gorgeous outside These bike lights, speaker, lantern and head torch all use the same power bank as a universal battery",
      "by":"Knog",
      "country":"AU",
      "currency":"aud",
      "endtime":"2016-11-26T07:42:38-05:00",
      "location":"Melbourne, AU",
      "percentagefunded":43,
      "numbackers":"19611",
      "state":"VIC",
      "title":"PWR: an ecosystem of outdoor products using one power source",
      "type":"Town",
      "url":"/projects/1951570531/pwr-an-ecosystem-of-outdoor-products-using-one-pow?ref=discovery"
   },
   {  
      "sno":64,
      "amtpledged":9884,
      "blurb":"The definitive documentary about the legendary Native Tongue Posse",
      "by":"Omar Akil",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-18T16:29:31-05:00",
      "location":"New York, NY",
      "percentagefunded":20,
      "numbackers":"19541",
      "state":"NY",
      "title":"The Native Tongue Posse Documentary",
      "type":"Town",
      "url":"/projects/589799990/the-native-tongue-posse-documentary?ref=discovery"
   },
   {  
      "sno":65,
      "amtpledged":26817,
      "blurb":"Our design philosophy embraces simplicity, enabling us to build a safe, high performance, and cost effective Hyperloop pod",
      "by":"Waterloop",
      "country":"CA",
      "currency":"cad",
      "endtime":"2016-11-18T19:39:52-05:00",
      "location":"Waterloo, Canada",
      "percentagefunded":134,
      "numbackers":"19349",
      "state":"ON",
      "title":"Waterloop: The Canadian SpaceX Hyperloop Competition Team",
      "type":"Town",
      "url":"/projects/1629380361/waterloop-the-canadian-spacex-hyperloop-competitio?ref=discovery"
   },
   {  
      "sno":66,
      "amtpledged":933349,
      "blurb":"Sound waves convert the beerâ€™s carbonation into densely compacted, uniform Micro-Foamâ„¢ bubbles unlocking that fresh-from-the-tap taste",
      "by":"Fizzics Home Beer Draft System",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-04T09:01:25-04:00",
      "location":"San Francisco, CA",
      "percentagefunded":1866,
      "numbackers":"18604",
      "state":"CA",
      "title":"Fizzics Waytap | Untap the full taste of beer with science",
      "type":"Town",
      "url":"/projects/161302347/fizzics-waytap-untap-the-full-taste-of-beer-with-s?ref=discovery"
   },
   {  
      "sno":67,
      "amtpledged":45469,
      "blurb":"Inspired by a true robbery",
      "by":"LudiCreations",
      "country":"DE",
      "currency":"usd",
      "endtime":"2016-10-30T23:55:00-04:00",
      "location":"Dusseldorf, Germany",
      "percentagefunded":4546,
      "numbackers":"18558",
      "state":"North Rhine-Westphalia",
      "title":"Steal This Game",
      "type":"Town",
      "url":"/projects/ludicreations/steal-this-game?ref=discovery"
   },
   {  
      "sno":68,
      "amtpledged":16653,
      "blurb":"Jailed for comics?! The true story of the only US artist convicted of obscenity, directed by cult filmmaker Frank Henenlotter",
      "by":"Anthony Sneed",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-17T21:00:00-05:00",
      "location":"Brooklyn, NY",
      "percentagefunded":41,
      "numbackers":"18220",
      "state":"NY",
      "title":"The Trial of Mike Diana",
      "type":"Zip",
      "url":"/projects/1300283850/the-trial-of-mike-diana?ref=discovery"
   },
   {  
      "sno":69,
      "amtpledged":13447,
      "blurb":"Pseudopod the weekly short horror fiction podcast is celebrating its 10th Halloween and is raising funds to pay their narrators",
      "by":"Escape Artists Inc",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-22T22:00:00-05:00",
      "location":"Atlanta, GA",
      "percentagefunded":43,
      "numbackers":"18209",
      "state":"GA",
      "title":"Pseudopod: Year 10",
      "type":"Town",
      "url":"/projects/1013714773/pseudopod-year-10?ref=discovery"
   },
   {  
      "sno":70,
      "amtpledged":238114,
      "blurb":"The first smart coffee instrument with a built-in scale and an app enables you to brew coffee with pour-over, immersion and cold drip",
      "by":"Anze Miklavec",
      "country":"SI",
      "currency":"usd",
      "endtime":"2016-12-17T08:00:50-05:00",
      "location":"Ljubljana, Slovenia",
      "percentagefunded":476,
      "numbackers":"18126",
      "state":"Ljubljana",
      "title":"GINA: Smart coffee instrument / by GOAT STORY",
      "type":"Town",
      "url":"/projects/goat-mug/gina-smart-coffee-instrument-by-goat-story?ref=discovery"
   },
   {  
      "sno":71,
      "amtpledged":21227,
      "blurb":"Pocket-size weekly planner full of tiny jokes, activities and nagging to (maybe???) help you keep your s*** together in the new year",
      "by":"Adam J Kurtz",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-17T07:35:14-05:00",
      "location":"Brooklyn, NY",
      "percentagefunded":816,
      "numbackers":"17765",
      "state":"NY",
      "title":"Unsolicited Advice: 2017 Weekly Planner",
      "type":"County",
      "url":"/projects/adamjk/unsolicited-advice-2017-weekly-planner?ref=discovery"
   },
   {  
      "sno":72,
      "amtpledged":236963,
      "blurb":"Banish messy cables and slow charging forever with ECLIPSE â€“ the new, neater way to charge your daily devices",
      "by":"Native Union",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-18T12:00:00-05:00",
      "location":"Los Angeles, CA",
      "percentagefunded":473,
      "numbackers":"17744",
      "state":"CA",
      "title":"ECLIPSE - Say Goodbye to Messy Cables",
      "type":"Town",
      "url":"/projects/nativeunion/eclipse-say-goodbye-to-messy-cables?ref=discovery"
   },
   {  
      "sno":73,
      "amtpledged":206691,
      "blurb":"A casual card game for grownups who feel like they're pretending",
      "by":"Jason Anarchy",
      "country":"CA",
      "currency":"cad",
      "endtime":"2016-10-31T10:06:02-04:00",
      "location":"Toronto, Canada",
      "percentagefunded":3444,
      "numbackers":"17739",
      "state":"ON",
      "title":"Pretending to Grownup",
      "type":"Town",
      "url":"/projects/drinkingquest/pretending-to-grownup?ref=discovery"
   },
   {  
      "sno":74,
      "amtpledged":1731,
      "blurb":"A new kind of interactive publication that encourages girls to be girls; independent, strong, smart, and proud of who they are",
      "by":"Bright Lite",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-26T13:44:49-05:00",
      "location":"Los Angeles, CA",
      "percentagefunded":17,
      "numbackers":"17733",
      "state":"CA",
      "title":"Bright Lite Magazine: For Girls, By Girls",
      "type":"Town",
      "url":"/projects/71736074/bright-lite-magazine-for-girls-by-girls?ref=discovery"
   },
   {  
      "sno":75,
      "amtpledged":368580,
      "blurb":"Font Awesome makes it easy to add vector icons and social logos to your website And Pro gives 1,000+ more icons and SVG support!",
      "by":"Dave Gandy",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-12-01T12:01:00-05:00",
      "location":"Cambridge, MA",
      "percentagefunded":1228,
      "numbackers":"17713",
      "state":"MA",
      "title":"Font Awesome 5",
      "type":"Town",
      "url":"/projects/232193852/font-awesome-5?ref=discovery"
   },
   {  
      "sno":76,
      "amtpledged":12091,
      "blurb":"Bowie's world debuts of Hunky Dory & Ziggy Stardust were at Friars Aylesbury We are creating a stunning statue in the Market Square",
      "by":"David Stopps for Friars Aylesbury",
      "country":"GB",
      "currency":"gbp",
      "endtime":"2016-12-06T06:38:11-05:00",
      "location":"Aylesbury, UK",
      "percentagefunded":12,
      "numbackers":"17614",
      "state":"England",
      "title":"David Bowie Statue - Aylesbury Market Square UK",
      "type":"Town",
      "url":"/projects/1980358464/david-bowie-statue-aylesbury-market-square-uk?ref=discovery"
   },
   {  
      "sno":77,
      "amtpledged":6344,
      "blurb":"A photography book exploring a family's journey through the hallucinatory wake of Hurricane Sandyâ€™s devastation",
      "by":"Michael Marcelle",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-27T08:20:56-05:00",
      "location":"Brooklyn, NY",
      "percentagefunded":31,
      "numbackers":"17218",
      "state":"NY",
      "title":"Kokomo, A Photography Book",
      "type":"County",
      "url":"/projects/1869229839/kokomo-a-photography-book?ref=discovery"
   },
   {  
      "sno":78,
      "amtpledged":83860,
      "blurb":"Meet the stylus that works like the pencil you grew up with Flip has the features of an active stylus without Bluetooth or batteries!",
      "by":"Lynktec",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-14T08:57:37-05:00",
      "location":"Chicago, IL",
      "percentagefunded":1118,
      "numbackers":"17184",
      "state":"IL",
      "title":"Flip! The Worldâ€™s Most Intuitive Smart Stylus",
      "type":"Town",
      "url":"/projects/lynktec/flip-the-worlds-most-intuitive-smart-stylus?ref=discovery"
   },
   {  
      "sno":79,
      "amtpledged":70593,
      "blurb":"An oversized archival art book collecting the unforgettable-yet-forgotten work of Herbert Crowley, and telling his remarkable story",
      "by":"Beehive Books",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-11T23:59:00-05:00",
      "location":"Philadelphia, PA",
      "percentagefunded":141,
      "numbackers":"17029",
      "state":"PA",
      "title":"The Temple of Silence: Forgotten Worlds of Herbert Crowley",
      "type":"Town",
      "url":"/projects/beehivebooks/the-temple-of-silence-forgotten-worlds-of-herbert?ref=discovery"
   },
   {  
      "sno":80,
      "amtpledged":92350,
      "blurb":"Root is more than just a robot that drives on walls It turns paper or whiteboards into an intuitive and interactive coding experience",
      "by":"Scansorial",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-29T22:00:00-05:00",
      "location":"Cambridge, MA",
      "percentagefunded":36,
      "numbackers":"16936",
      "state":"MA",
      "title":"Root - A robot to teach coding",
      "type":"Town",
      "url":"/projects/1509453982/root-a-robot-to-teach-coding?ref=discovery"
   },
   {  
      "sno":81,
      "amtpledged":24940,
      "blurb":"The world's fastest and most affordable gel manicure kits! DIY gel nails (with a cute macaron lamp) when you want, where you want!",
      "by":"Christina Kao",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-22T00:00:00-05:00",
      "location":"Birmingham, AL",
      "percentagefunded":249,
      "numbackers":"16850",
      "state":"AL",
      "title":"LE MINI MACARON | Best 15Min Gel Nail Kit | The Perfect Gift",
      "type":"Town",
      "url":"/projects/1643301879/le-mini-macaron-best-15min-gel-nail-kit-the-perfec?ref=discovery"
   },
   {  
      "sno":82,
      "amtpledged":61377,
      "blurb":"A Fluid Smart-Home and Apps controller, Bixi senses your in-air gestures and commands the smart devices for a touch-free use!",
      "by":"Bixi",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-12-03T11:35:07-05:00",
      "location":"Los Angeles, CA",
      "percentagefunded":245,
      "numbackers":"16732",
      "state":"CA",
      "title":"Bixi: Control Any Smart Device by Simply Waving Your Hand!",
      "type":"Town",
      "url":"/projects/1860920533/bixi-control-any-smart-device-by-simply-waving-you?ref=discovery"
   },
   {  
      "sno":83,
      "amtpledged":91680,
      "blurb":"The multi-award winning dark fantasy RPG from France, between Ravenloft, Game of Thrones and Call of Cthulhu",
      "by":"Jim Searcy",
      "country":"FR",
      "currency":"usd",
      "endtime":"2016-11-18T04:00:00-05:00",
      "location":"Paris, France",
      "percentagefunded":458,
      "numbackers":"16538",
      "state":"Ile-de-France",
      "title":"Shadows of Esteren - A Medieval Horror RPG: Dearg",
      "type":"Town",
      "url":"/projects/1176616619/shadows-of-esteren-a-medieval-horror-rpg-dearg?ref=discovery"
   },
   {  
      "sno":84,
      "amtpledged":27997,
      "blurb":"3D printed solar system of your personal date, custom made with NASA's data pendant / keyring ideal for Astronomy & Science lovers",
      "by":"govy",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-15T06:00:00-05:00",
      "location":"New York, NY",
      "percentagefunded":27997,
      "numbackers":"16537",
      "state":"NY",
      "title":"SpaceTime Coordinates Memento ~ your personal place in space",
      "type":"Town",
      "url":"/projects/govy/spacetime-coordinates-memento?ref=discovery"
   },
   {  
      "sno":85,
      "amtpledged":296979,
      "blurb":"Life's hard when you're a Lich Join Steve and his friends during their everyday lives down in the dungeon (Hardcover, 400 pages)",
      "by":"Acceptable Comics",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-10-31T23:59:00-04:00",
      "location":"Bristol, RI",
      "percentagefunded":1649,
      "numbackers":"16459",
      "state":"RI",
      "title":"Steve Lichman - Volume 2",
      "type":"Town",
      "url":"/projects/stevelichman/steve-lichman-volume-2?ref=discovery"
   },
   {  
      "sno":86,
      "amtpledged":5384,
      "blurb":"'Gaelic Americana' singer-songwriter Kyle Carey is making a new album! Will you join her on the journey?",
      "by":"Kyle Carey",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-30T13:24:51-05:00",
      "location":"Brooklyn, NY",
      "percentagefunded":19,
      "numbackers":"16408",
      "state":"NY",
      "title":"The Art of Forgetting' - Kyle Carey's New Album",
      "type":"County",
      "url":"/projects/kylecarey/the-art-of-forgetting-kyle-careys-new-album?ref=discovery"
   },
   {  
      "sno":87,
      "amtpledged":104316,
      "blurb":"Caitlin Moran makes an indecent proposal to Della to save RAISED BY WOLVES & give the world more 'Ripley-from-Alien'-style parenting",
      "by":"Caitlin Moran and Caroline Moran",
      "country":"GB",
      "currency":"gbp",
      "endtime":"2016-11-20T18:00:00-05:00",
      "location":"Wolverhampton, UK",
      "percentagefunded":32,
      "numbackers":"16335",
      "state":"England",
      "title":"Save The Wolves!",
      "type":"Town",
      "url":"/projects/raisedbywolves/save-the-wolves?ref=discovery"
   },
   {  
      "sno":88,
      "amtpledged":21541,
      "blurb":"An authentic Jewish delicatessen open seven days a week, where traditional recipes are made expertly in house with great love and care",
      "by":"Monty's Deli",
      "country":"GB",
      "currency":"gbp",
      "endtime":"2016-11-13T04:34:05-05:00",
      "location":"London, UK",
      "percentagefunded":43,
      "numbackers":"16180",
      "state":"England",
      "title":"Monty's Deli - A real Jewish deli",
      "type":"Town",
      "url":"/projects/1061292574/montys-deli-a-real-jewish-deli?ref=discovery"
   },
   {  
      "sno":89,
      "amtpledged":12959,
      "blurb":"A highly-produced storytelling podcast about Apple and the community around it 8 brand new episodes, coming Summer 2017",
      "by":"Mark Bramhill",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-17T20:00:00-05:00",
      "location":"Houston, TX",
      "percentagefunded":129,
      "numbackers":"16038",
      "state":"TX",
      "title":"Welcome to Macintosh: Season 3",
      "type":"Town",
      "url":"/projects/bramhill/welcome-to-macintosh-season-3?ref=discovery"
   },
   {  
      "sno":90,
      "amtpledged":198896,
      "blurb":"Your alarm clock is now a personal assistant By learning about your agenda and hobbies, Bonjour helps make the most of each day",
      "by":"BONJOUR",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-12-05T10:59:46-05:00",
      "location":"Los Angeles, CA",
      "percentagefunded":397,
      "numbackers":"15998",
      "state":"CA",
      "title":"Bonjour | Smart Alarm Clock with Artificial Intelligence",
      "type":"Town",
      "url":"/projects/1450781303/bonjour-smart-alarm-clock-with-artificial-intellig?ref=discovery"
   },
   {  
      "sno":91,
      "amtpledged":55522,
      "blurb":"A 10-minute social deduction game for 4-8 monsters Featuring gorgeous, thematic art and 12 roles with unique abilities!",
      "by":"Blue Beard Entertainment",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-11T20:00:00-05:00",
      "location":"St Louis, MO",
      "percentagefunded":694,
      "numbackers":"15824",
      "state":"MO",
      "title":"Draculaâ€™s Feast: A monstrous game of secrets and deduction",
      "type":"Town",
      "url":"/projects/peterchayward/draculas-feast-a-monstrous-game-of-secrets-and-ded?ref=discovery"
   },
   {  
      "sno":92,
      "amtpledged":11621,
      "blurb":"A new documentary exploring the growing privatization of public schools, and the impact on America's most vulnerable children",
      "by":"Sarah Mondale",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-18T21:16:05-05:00",
      "location":"Suffern, NY",
      "percentagefunded":36,
      "numbackers":"15802",
      "state":"NY",
      "title":"BACKPACK FULL OF CASH: a new film, narrated by Matt Damon",
      "type":"Town",
      "url":"/projects/1974989045/backpack-full-of-cash-a-new-film-narrated-by-matt?ref=discovery"
   },
   {  
      "sno":93,
      "amtpledged":7542,
      "blurb":"The Real Story of Ruth the Tooth is an adventurous children's book that is a special kind of 3D and comes with a read along record",
      "by":"Tripper Dungan",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-10-31T19:06:38-04:00",
      "location":"Portland, OR",
      "percentagefunded":91,
      "numbackers":"15736",
      "state":"OR",
      "title":"The Real Story of Ruth the Tooth, 3D Book and Record",
      "type":"Town",
      "url":"/projects/tripperdungan/the-real-story-of-ruth-the-tooth-3d-book-and-recor?ref=discovery"
   },
   {  
      "sno":94,
      "amtpledged":41168,
      "blurb":"Strange Matter Coffee is opening a scratch bakery featuring craft doughnuts with vegan and gluten free options!",
      "by":"Cara Nader",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-10-30T11:25:38-04:00",
      "location":"Lansing, MI",
      "percentagefunded":102,
      "numbackers":"15623",
      "state":"MI",
      "title":"Doughnuts with love by Strange Matter Coffee",
      "type":"Town",
      "url":"/projects/1174317590/doughnuts-with-love-by-strange-matter-coffee?ref=discovery"
   },
   {  
      "sno":95,
      "amtpledged":180642,
      "blurb":"Knit with ultrasoft, naturally insulating llama fiber, the Libre is engineered for the city, the summit, and everything in between",
      "by":"Cotopaxi",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-16T15:27:10-05:00",
      "location":"Salt Lake City, UT",
      "percentagefunded":903,
      "numbackers":"15352",
      "state":"UT",
      "title":"The Libre Sweater: Insulator Outer layer Epic enabler",
      "type":"Town",
      "url":"/projects/cotopaxi/the-libre-sweater-insulator-outer-layer-epic-enabl?ref=discovery"
   },
   {  
      "sno":96,
      "amtpledged":439909,
      "blurb":"An Android Nougat-powered device exclusive on Kickstarter for $99 Engineered to be a 4K TV set-top box, gaming console, and PC in one",
      "by":"Jide Tech",
      "country":"CN",
      "currency":"usd",
      "endtime":"2016-11-19T10:57:37-05:00",
      "location":"Beijing, China",
      "percentagefunded":175,
      "numbackers":"15251",
      "state":"Beijing",
      "title":"Remix IO - A 4K, Nougat-powered, All-in-One device",
      "type":"Town",
      "url":"/projects/jidetech/remix-io-a-4k-nougat-powered-all-in-one-device?ref=discovery"
   },
   {  
      "sno":97,
      "amtpledged":318367,
      "blurb":"Build it Code it Fly it The First Modular Drone Transforms into Whatever You Want",
      "by":"Makeblock",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-12-14T08:00:00-05:00",
      "location":"San Francisco, CA",
      "percentagefunded":318,
      "numbackers":"15129",
      "state":"CA",
      "title":"Airblock: The Modular and Programmable Starter Drone",
      "type":"Town",
      "url":"/projects/1818505613/airblock-the-modular-and-programmable-starter-dron?ref=discovery"
   },
   {  
      "sno":98,
      "amtpledged":1416,
      "blurb":"The premier of Triangle Theory, a dance about triangles in three parts, at Roulette Intermedium November 28-30, 2016",
      "by":"Kyli Kleven",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-11-13T23:59:00-05:00",
      "location":"Brooklyn, NY",
      "percentagefunded":31,
      "numbackers":"15029",
      "state":"NY",
      "title":"Triangle Theory",
      "type":"County",
      "url":"/projects/872122110/triangle-theory?ref=discovery"
   },
   {  
      "sno":99,
      "amtpledged":130010,
      "blurb":"Help us publish the first exact copy of Fortunato Deperoâ€™s 1927 iconic work of avant-garde graphic design and book-making",
      "by":"Designers & Books",
      "country":"US",
      "currency":"usd",
      "endtime":"2016-12-01T23:59:00-05:00",
      "location":"Manhattan, NY",
      "percentagefunded":52,
      "numbackers":"14964",
      "state":"NY",
      "title":"The Bolted Book Facsimile: An Exact Copy of Depero Futurista",
      "type":"County",
      "url":"/projects/1204158310/the-bolted-book-facsimile-an-exact-copy-of-depero?ref=discovery"
   },
   {  
      "sno":100,
      "amtpledged":10573,
      "blurb":"Helios is a modular touch screen wall light that turns walls into a canvas for illumination, using your hand as the brush",
      "by":"Dyena",
      "country":"GB",
      "currency":"gbp",
      "endtime":"2016-12-17T09:44:39-05:00",
      "location":"Southampton, UK",
      "percentagefunded":10,
      "numbackers":"14952",
      "state":"England",
      "title":"Helios Touch Modular Lighting",
      "type":"Town",
      "url":"/projects/1987956413/helios-touch-modular-lighting?ref=discovery"
   }
];
